name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      APIKEY: ${{ secrets.NUGET_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack src -c Release -o ./artifacts/bin
    - name: Publish
      run: dotnet nuget push ./artifacts/bin/*.nupkg --api-key "$SUPER_SECRET" --source https://api.nuget.org/v3/index.json
