name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.2.21505.57
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Pack
      run: dotnet pack src -c Release -o ./artifacts/bin

  deploy:

    runs-on: ubuntu-latest

    env:
      APIKEY: ${{ secrets.NUGET_API_KEY }}

    environment:
      name: Deploy

    steps:
    - name: Nuget
      run: dotnet nuget push ./artifacts/bin/*.nupkg --api-key "$APIKEY" --source https://api.nuget.org/v3/index.json


